from __future__ import annotations

from email_node.flow_families.order.heuristics import (
    CHROME_LINE_PATTERNS,
    FILLER_ENTITY_PATTERNS,
    FOOTER_CUTOFF_PATTERNS,
    IGNORE_LINE_PATTERNS,
    IMPORTANT_LINK_PATTERNS,
    PROMO_MARKER_PATTERNS,
    STOP_MARKER_PATTERNS,
    TRACKING_HOST_PATTERNS,
    TRANSACTIONAL_ANCHOR_PATTERNS,
)


__all__ = [
    "CHROME_LINE_PATTERNS",
    "FILLER_ENTITY_PATTERNS",
    "FOOTER_CUTOFF_PATTERNS",
    "IGNORE_LINE_PATTERNS",
    "IMPORTANT_LINK_PATTERNS",
    "PROMO_MARKER_PATTERNS",
    "STOP_MARKER_PATTERNS",
    "TRACKING_HOST_PATTERNS",
    "TRANSACTIONAL_ANCHOR_PATTERNS",
]
